services:

  next:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jidelna_ai_next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - jidelna_ai_network
    hostname: next


  postgres:
    image: postgres:latest
    container_name: jidelna_ai_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jidelna_ai
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - jidelna_ai_network
    hostname: postgres


networks:
  jidelna_ai_network: