FROM node:22-alpine3.20

WORKDIR /app

# Install PNPM usin NPM
RUN npm install -g pnpm

# Create a limited user (to avoid using root)
RUN addgroup -S build_group && \
    adduser -S build -G build_group && \
    chown build:build_group /app

# Switch to the limited user
USER build

# Copy files with project dependencies
COPY package.json pnpm-lock.yaml ./

# Install dependencies using PNPM
RUN pnpm install --frozen-lockfile

# Copy the rest of the codebase
COPY --chown=build:build_group . .

# Epose development port
EXPOSE 3000

# Run development 
CMD ["pnpm", "run", "dev"]
