services:

  postgres:
    image: postgres:latest
    container_name: jidelna_ai_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jidelna_ai
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - jidelna_ai_network
    hostname: postgres

  next:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    # restart: unless-stopped
    volumes:
      - ./prisma/migrations:/app/prisma/migrations
    networks:
      - jidelna_ai_network
    hostname: next

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json


networks:
  jidelna_ai_network:
